steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=us-docker.pkg.dev/$PROJECT_ID/cloudbuilders/skaffold:alpha', '.']

images: ['us-docker.pkg.dev/$PROJECT_ID/cloudbuilders/skaffold:alpha']
tags: ['cloud-builders-community']
