# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###########################################################
# This is a GCP CloudBuild Trigger config file. The trigger
# is to be used to build and publish the latest release
# artifacts to repostiories (container-image and maven).
# The trigger associated to this cloudbuild confiuration
# needs to be manually RUN pointing to the release-branch
###########################################################

steps:
  ###########################################################
  # Deploy the latest release manifests to the main cluster
  ###########################################################
- id: 'deploy-to-k8s-main'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.36.0'
  entrypoint: bash
  args:
  - -c
  - |
    gcloud container clusters get-credentials --zone $_MAIN_CLUSTER_ZONE $_MAIN_CLUSTER
    kubectl create namespace $_MAIN_NS-db
    kubectl create namespace $_MAIN_NS-inmemory

    skaffold run -p release -f=skaffold.yaml --namespace=$_MAIN_NS-db
    skaffold run -p release,inmemory -f=skaffold.yaml --namespace=$_MAIN_NS-inmemory
  # waitFor: commented out, so this step waits for all previous steps

timeout: 1800s
logsBucket: 'gs://pos-cloudbuild-logs'
options:
    logging: GCS_ONLY