# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###########################################################
# This is a GCP CloudBuild Trigger config file. The trigger
# can be used to publish the built artifacts to
# repostiories (container-image and maven)
###########################################################

steps:
  ###########################################################
  # publish jars to artifact registry
  ###########################################################
- id: 'publish-jars'
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
  - -c
  - |
    ./mvnw clean deploy
  # indicates that the step need not wait for any other step
  waitFor: [ '-' ]

 ###########################################################
  # skaffold deploy to kubernetes cluster
  ###########################################################
- id: 'publish-images'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.36.0'
  entrypoint: bash
  args:
  - -c
  - |
    ./mvnw install
    skaffold build -p dev -f=skaffold.yaml --default-repo=us-docker.pkg.dev/$PROJECT_ID/$_POS_IMAGE_REPO --tag=v$VERSION
  # indicates that the step need not wait for any other step
  waitFor: [ '-' ]

timeout: 1800s
logsBucket: 'gs://pos-cloudbuild-logs'
options:
    logging: GCS_ONLY